
version: 3
jobs:
  build:
    docker:
    steps:
      - checkout
      - restore_cache: 
          key: deps1-{{ .Branch }}-{{ checksum "myenv.yml" }}
      - run: 
          command: |
            chmod +x run.sh
            ./run.sh
      - save_cache: # special step to save dependency cache
          key: deps1-{{ .Branch }}-{{ checksum "myenv.yml" }}
          paths:
            - "venv"
      - store_artifacts:
          path: ./Index.html
          destination: test-reports
